#!/bin/sh

#SBATCH --job-name=ds002748-fmriprep
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002748-fmriprep/.reproman/jobs/local/20220711-222344-a6a6/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002748-fmriprep/.reproman/jobs/local/20220711-222344-a6a6/stderr

#SBATCH --nodes=17
#SBATCH --ntasks=66
#SBATCH --time=48:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002748-fmriprep/.reproman/jobs/local/20220711-222344-a6a6

module load launcher
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 65); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

"$LAUNCHER_DIR"/paramrun